INSERT INTO tb_product (name, price, image_Uri, description) VALUES ('Churrasquinho', 10.0, '/churrasquinho.jpg', 'Espetinho de frango com mussarela, orégano, molho especial e tempero da casa.');
INSERT INTO tb_product (name, price, image_Uri, description) VALUES ('Copo Amendoin', 9.0, '/amendoin.jpg', 'Copo de amendoin, bem torradinho.');
INSERT INTO tb_product (name, price, image_Uri, description) VALUES ('Suco de lanranja', 8.0, '/sucodelaranja.jpg', 'Suco de laranja, geladinho e bem doce');
INSERT INTO tb_product (name, price, image_Uri, description) VALUES ('Pastel de frango', 7.0, '/pasteldefrango.jpg', 'Pastel frito com recheio cremoso de frango');
INSERT INTO tb_product (name, price, image_Uri, description) VALUES ('Tapioca comum', 5.0, '/tapiocacomum.jpg', 'Tapioca comum');
INSERT INTO tb_product (name, price, image_Uri, description) VALUES ('Tapica com manteiga', 7.0, '/tapiocacommanteiga.jpg', 'Tapioca com manteiga.');
INSERT INTO tb_product (name, price, image_Uri, description) VALUES ('Tapioca com carne seca', 15.0, '/tapiocacomcarneseca.jpg', 'Tapioca com recheio de carne seca.');
INSERT INTO tb_product (name, price, image_Uri, description) VALUES ('Tapioca com queijo e presunto', 10.0, '/tapiocacompreequeijo.jpg', 'Tapioca com queijo e presunto');

INSERT INTO tb_order (status, latitude, longitude, address, moment) VALUES (0, -23.561680, -46.656139, 'Avenida Mendonça furtado, 1300', TIMESTAMP WITH TIME ZONE '2021-01-01T10:00:00Z');
INSERT INTO tb_order (status, latitude, longitude, address, moment) VALUES (1, -22.946779, -43.217753, 'Avenida Mendonça furtado, 1300', TIMESTAMP WITH TIME ZONE '2021-01-01T15:00:00Z');
INSERT INTO tb_order (status, latitude, longitude, address, moment) VALUES (0, -25.439787, -49.237759, 'Avenida Mendonça furtado, 1300', TIMESTAMP WITH TIME ZONE '2021-01-01T16:00:00Z');
INSERT INTO tb_order (status, latitude, longitude, address, moment) VALUES (0, -23.561680, -46.656139, 'Avenida Mendonça furtado, 1300', TIMESTAMP WITH TIME ZONE '2021-01-01T12:00:00Z');
INSERT INTO tb_order (status, latitude, longitude, address, moment) VALUES (1, -23.561680, -46.656139, 'Avenida Mendonça furtado, 1300', TIMESTAMP WITH TIME ZONE '2021-01-01T08:00:00Z');
INSERT INTO tb_order (status, latitude, longitude, address, moment) VALUES (0, -23.561680, -46.656139, 'Avenida Mendonça furtado, 1300', TIMESTAMP WITH TIME ZONE '2021-01-01T14:00:00Z');
INSERT INTO tb_order (status, latitude, longitude, address, moment) VALUES (0, -23.561680, -46.656139, 'Avenida Mendonça furtado, 1300', TIMESTAMP WITH TIME ZONE '2021-01-01T09:00:00Z');

INSERT INTO tb_order_product (order_id, product_id) VALUES (1 , 1);
INSERT INTO tb_order_product (order_id, product_id) VALUES (1 , 4);
INSERT INTO tb_order_product (order_id, product_id) VALUES (2 , 2);
INSERT INTO tb_order_product (order_id, product_id) VALUES (2 , 5);
INSERT INTO tb_order_product (order_id, product_id) VALUES (2 , 8);
INSERT INTO tb_order_product (order_id, product_id) VALUES (3 , 3);
INSERT INTO tb_order_product (order_id, product_id) VALUES (3 , 4);
INSERT INTO tb_order_product (order_id, product_id) VALUES (4 , 2);
INSERT INTO tb_order_product (order_id, product_id) VALUES (4 , 6);
INSERT INTO tb_order_product (order_id, product_id) VALUES (5 , 4);
INSERT INTO tb_order_product (order_id, product_id) VALUES (5 , 6);
INSERT INTO tb_order_product (order_id, product_id) VALUES (6 , 5);
INSERT INTO tb_order_product (order_id, product_id) VALUES (6 , 1);
INSERT INTO tb_order_product (order_id, product_id) VALUES (7 , 7);
INSERT INTO tb_order_product (order_id, product_id) VALUES (7 , 5);